//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REM_FIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Besinler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Besinler()
        {
            this.TüketildiğiÖğün = new HashSet<TüketildiğiÖğün>();
        }
    
        public int BesinID { get; set; }
        public string BesinAdı { get; set; }
        public int Birimi { get; set; }
        public int Kalori { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TüketildiğiÖğün> TüketildiğiÖğün { get; set; }
    }
}
