//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REM_FIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class TüketildiğiÖğün
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TüketildiğiÖğün()
        {
            this.Besinlers = new HashSet<Besinler>();
        }
    
        public int BesinID { get; set; }
        public int TüketildiğiÖğün1 { get; set; }
        public System.DateTime TükedildiğiTarih { get; set; }
        public double Miktarı { get; set; }
        public Nullable<int> User_UserID { get; set; }
    
        public virtual Kullanıcılar Kullanıcılar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Besinler> Besinlers { get; set; }
    }
}
