//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REM_FIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanıcılar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanıcılar()
        {
            this.TüketildiğiÖğün = new HashSet<TüketildiğiÖğün>();
        }
    
        public int UserID { get; set; }
        public int KullanıcıTipi { get; set; }
        public string Ad { get; set; }
        public string Soyadı { get; set; }
        public string EMail { get; set; }
        public Nullable<System.DateTime> DoğumTarihi { get; set; }
        public int Cinsiyeti { get; set; }
        public string Sifre { get; set; }
        public double Kilo { get; set; }
        public double Boy { get; set; }
        public System.DateTime KayıtTarihi { get; set; }
        public double GünlülKaloriIhtiyacı { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TüketildiğiÖğün> TüketildiğiÖğün { get; set; }
    }
}
